set nocompatible              " be iMproved
filetype off                  " required!

syntax on
set number
" set encoding=utf-8
" set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,chinese,cp936  " 查看encoding-name帮助来确定
set expandtab  " 自动展开tab成空格
set shiftwidth=4  " 每层缩进2空格
set tabstop=4  " tab宽度

set guioptions-=m  " 去掉GUI的菜单
set guioptions-=T  " 去掉GUI的工具栏

" 显示空格
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

" Backspace在Insert mode下异常
set backspace=2
set backspace=indent,eol,start

" 对Windows进行设置
if has("win32")
  set guifont=Consolas:h11.5:cDEFAULT
  " set guifontwide=YaHei\ Consolas\ Hybrid:h11
  au GUIEnter * simalt ~x  " 最大化窗口
endif

" 自动切换工作目录
set autochdir

set t_Co=256
" colorscheme desert

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" ColorScheme DsertEx
Plugin 'vim-scripts/desertEx'
colorscheme desertEx

" Emmet
Bundle 'mattn/emmet-vim'
" Emmet Configurations
" let g:user_emmet_mode='n'  " 只启用normal模式功能
" let g:user_emmet_mode='inv'  " 启用所有模式功能，下同
" let g:user_emmet_mode='a'
" 只对html/css启用
" let g:user_emmet_install_global = 0
" autocmd FileType html,css EmmetInstall

" AutoClose
Bundle 'AutoClose'

" 识别文件编码
Bundle 'FencView.vim'

" ShowTrailingWhitespace
Bundle 'ShowTrailingWhitespace'

" EasyMotion
Bundle 'EasyMotion'

" The-NERD-tree
Bundle 'The-NERD-tree'
" 在 vim 启动的时候默认开启 NERDTree（autocmd 可以缩写为 au）
" autocmd vimEnter * NERDTree

" The-NERD-Commenter 快速注释
Bundle 'The-NERD-Commenter'

" Markdown-syntax Markdown到HTML
Bundle 'Markdown-syntax'

" vim-sacla
Bundle 'derekwyatt/vim-scala'

" html5.vim
Bundle 'othree/html5.vim'

" play2vim
Bundle 'gre/play2vim'

" UltiSnips
Bundle 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
" let g:UltiSnipsEditSplit="vertical"

" vim-autoformat
" Bundle 'Chiel92/vim-autoformat'

" Markdown Bundle 'Markdown'

" YouCompleteMe Bundle 'YouCompleteMe'

" vim_indent-guides
Bundle 'nathanaelkane/vim-indent-guides'
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1

" CtrlP
Bundle 'kien/ctrlp.vim'
" Change the default mapping and the default command to invoke CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" Matchit
Bundle 'edsono/vim-matchit'

Bundle 'bling/vim-airline'

Bundle 'scrooloose/syntastic'

filetype plugin indent on     " required!
